import os

DEFAULT_AVAIABLE_KARMA = int(os.getenv("DEFAULT_AVAIABLE_KARMA", 10))
DEFAULT_AVAIABLE_KARMA_COOLDOWN = int(os.getenv("DEFAULT_KARMA_COOLDOWN", 24 * 60 * 60))
DEFAULT_PAGE_SIZE = int(os.getenv("DEFAULT_PAGE_SIZE", 10))
MAXIMUM_PAGE_SIZE = int(os.getenv("MAXIMUM_PAGE_SIZE", 25))

CURRENT_VERSION = "1.2.6"
